### ISSUE TITLE
关于图片问答的一些小建议

### ISSUE THREAD

**Issue by mintianzan** [kexue-z/nonebot-plugin-word-bank3#3]
您好，在使用wb2的过程中，我发现wb2可以很好地支持问文字-答图片的操作；但是问图片-答文字或图片的操作会出现一些小问题。特别是在qq的环境下，收藏表情的cq码和把收藏表情保存下来发图片的cq码不一样，而且很多时候机器人接受到同一张图片的cq码也不一样。
是否可以考虑：
1.用多条消息接受问答
    例如：用户发：“问答”
               机器人发：“请发送问句”
               用户发：“[图片1]”
               机器人发：“请发送答句”
               用户发：“[图片2]或文字”
因为大多数用户使用手机qq不能把表情和文字同时并且按照顺序发出，所以这种方式能更好地支持表情问答以及长串问答。
2.保存图片hash码
参考nonebot_plugin_picsbank，这个插件按照图片像素之间的大小对比生成hash值
可以适用于图像有细微差距的情况
3.修改图片保存形式
目前图像文件和json文件在同一路径下以.image的形式保存，是否可以直接按照图片原本格式保存，这样的话便于检查修改
也可以考虑给图片文件同样生成数据库，保存上传用户、关键词（？）、概率（？）等信息，这样或许能够更好地兼容其他插件对资源的使用？

**Comment by kexue-z** [comment]
可以考虑，但是没精力更新了~5555~ 

wb3 也没有正式发版。。。
